version: '2'
services:
  registry:
    image: sqshq/piggymetrics-registry
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: sqshq/piggymetrics-gateway
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    image: sqshq/piggymetrics-auth-service
    restart: always
    environment:
      NOTIFICATION_SERVICE_PASSWORD:
      STATISTICS_SERVICE_PASSWORD:
      ACCOUNT_SERVICE_PASSWORD:
      MONGODB_PASSWORD:
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    build: mongodb
    image: sqshq/piggymetrics-auth-mongodb
    restart: always
    environment:
      MONGODB_PASSWORD:
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    image: sqshq/piggymetrics-account-service
    restart: always
    environment:
      ACCOUNT_SERVICE_PASSWORD:
      MONGODB_PASSWORD:
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    build: mongodb
    image: sqshq/piggymetrics-account-mongodb
    restart: always
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD:
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-service:
    image: sqshq/piggymetrics-statistics-service
    restart: always
    environment:
      STATISTICS_SERVICE_PASSWORD:
      MONGODB_PASSWORD:
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-mongodb:
    build: mongodb
    image: sqshq/piggymetrics-statistics-mongodb
    restart: always
    environment:
      MONGODB_PASSWORD:
    logging:
      options:
        max-size: "10m"
        max-file: "10"
