security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: password
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  data:
    mongodb:
      host: account-mongodb
      username: service
      password: ${MONGODB_PASSWORD}
      database: piggymetrics

logging:
  level:
    org.springframework.security: DEBUG

server:
  context-path: /statistics
  port: 8000